version: "3.8"

services:
  # sql for microservices
  # docker run --restart unsless-stopped -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=yourStrong(!)Password" -p 1433:1433 -d mcr.microsoft.com/mssql/server:2022-latest
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Qwer1234!
    ports:
      - 1433:1433

  # rabbitmq for async microservice communication
  # docker run --name rabbitmq --restart unless-stopped -p 5672:5672 -p 15672:15672 rabbitmq:3-management
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
    ports:
      - 5672:5672
      - 15672:15672

  # datalust/seq for centralized logging both ASP.NET Core and Node.js apps.
  # docker run --name seq --restart unless-stopped -e ACCEPT_EULA=Y  -v seq-logs:/data -p 80:80 -p 5341:5341 datalust/seq
  seq:
    image: datalust/seq
    container_name: seq
    restart: unless-stopped
    environment: 
      - ACCEPT_EULA=Y
    ports:
      - 80:80
      - 5341:5341
    volumes:
      - seq-logs:/data

volumes:
  seq-logs: